### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by hartwork** [JanKleprlik/AudioVisualiser#1]
Hi @JanKleprlik, very nice project! :+1: 

I'd be interested to compile and try this on Linux. If I succeed in making a small CMake based build system for this project, would a pull request adding that plus a small CI based on GitHub Actions to catch future build breakage be welcome?

Best, Sebastian

**Comment by JanKleprlik** [comment]
Hi @hartwork ,

yes of course.  I don't plan on adding any features or working on this project anymore in the future. But I will gladly accept your PR. If you need any help, let me know.

**Comment by hartwork** [comment]
@JanKleprlik cool! Got it to work now, fun to watch, pull request upcoming! :smiley:

**Comment by hartwork** [comment]
@JanKleprlik any thoughts on pull request #3?

PS: In case the licensing aspect seems tiring or could use in depth discussion or explanation, I'm happy to jump in a voice call some time to save us a few pages of typing :smiley:

**Comment by JanKleprlik** [comment]
Merged. Thanks again, sorry for the delay.
